<a href="https://colab.research.google.com/github/knagabharathi/Python/blob/main/large_Data_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd, numpy as np

In [8]:
dfd = pd.read_csv('directors.csv')
dfm = pd.read_csv('movies.csv')

FileNotFoundError: ignored

# New Section

In [4]:
dfd.head()

   Unnamed: 0      director_name    id gender
0           0      James Cameron  4762   Male
1           1     Gore Verbinski  4763   Male
2           2         Sam Mendes  4764   Male
3           3  Christopher Nolan  4765   Male
4           4     Andrew Stanton  4766   Male

In [27]:
dfd.drop(['Unnamed: 0'],axis=1,inplace=True)

In [28]:
dfm.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [20]:
dfm.drop(['Unnamed: 0'],axis=1,inplace=True)

In [24]:
dfm.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [29]:
data = pd.merge(dfd,dfm,left_on='id',right_on='director_id',how='left')

In [30]:
data.iloc[:5,:3]

   director_name  id_x gender
0  James Cameron  4762   Male
1  James Cameron  4762   Male
2  James Cameron  4762   Male
3  James Cameron  4762   Male
4  James Cameron  4762   Male

In [1]:
dfd.head()

NameError: ignored

In [1]:
import pandas as pd
df1 = pd.DataFrame({"name": ['tobey', 'peter', 'chris', 'pratt'],'chem_score':[10, 9, 8, 7], 'phy_score':[7, 8, 9, 10], 'Hindi_score':[9, 9, 9, 9]})
df2 = pd.DataFrame({"name": ['chris', 'pratt', 'andrew', 'tom'],'chem_score':[10, 10, 10, 9], 'maths_score':[6, 6, 7, 9], 'eng_score':[9, 10, 10, 9]})

In [2]:
df1.head()

    name  chem_score  phy_score  Hindi_score
0  tobey          10          7            9
1  peter           9          8            9
2  chris           8          9            9
3  pratt           7         10            9

In [3]:
df2

     name  chem_score  maths_score  eng_score
0   chris          10            6          9
1   pratt          10            6         10
2  andrew          10            7         10
3     tom           9            9          9

In [9]:
data = pd.merge(df1,df2,on='name',how='outer')
data.sum(axis=1)

<ipython-input-9-8d11a0adaae0>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.sum(axis=1)

0    26.0
1    26.0
2    51.0
3    52.0
4    27.0
5    27.0
dtype: float64

In [12]:
data.groupby(['name']).sum()

,chem_score_x,phy_score,Hindi_score,chem_score_y,maths_score,eng_score
name,,,,,,
andrew,0.0,0.0,0.0,10.0,7.0,10.0
chris,8.0,9.0,9.0,10.0,6.0,9.0
peter,9.0,8.0,9.0,0.0,0.0,0.0
pratt,7.0,10.0,9.0,10.0,6.0,10.0
tobey,10.0,7.0,9.0,0.0,0.0,0.0
tom,0.0,0.0,0.0,9.0,9.0,9.0

In [19]:
data['avg_score']= data.iloc[:,1:].mean(axis=1).round(2)

In [34]:
data1=pd.concat([df1,df2],axis=0)
l =data1['chem_score'].mean()
l

9.125

In [31]:
import numpy as np
a = np.array(data['avg_score'][[2,3]])

In [37]:
list(a)

[8.5, 8.67]

In [38]:
x =[]
x.append(l)
x.append(list(a))

x

[9.125, [8.5, 8.67]]

In [7]:
import pandas as pd, numpy as np

In [8]:
data = pd.read_csv('Stock_py1.txt')

In [9]:
data.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [13]:
data.StockCode.nunique()

5305

In [11]:
data.shape

(1067371, 8)

In [12]:
data.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France