<a href="https://colab.research.google.com/github/knagabharathi/Python/blob/main/Pandas_4_pharma_exp_analysis_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.Pivot pandas

Which of the given option(s) are the right method and syntax for pivoting the below-mentioned dataframe such that each customer would have a value that is the total quantity of a particular type of accessories he holds? In the code,

In [ ]:
import pandas as pd,numpy as np

In [ ]:
df = pd.DataFrame({
  "Accessories": ["Laptop", "Laptop", "Ipad", "Ipad", "Tablet", "Laptop"],
  "customer": ["Andrew", "Andrew", "Tom", "Andrew", "Tobey", "Peter"],
  "quantity": [1, 2, 2, 3, 1, 2],
})

In [ ]:
df

  Accessories customer  quantity
0      Laptop   Andrew         1
1      Laptop   Andrew         2
2        Ipad      Tom         2
3        Ipad   Andrew         3
4      Tablet    Tobey         1
5      Laptop    Peter         2

In [ ]:
df.pivot(index="Accessories", columns="customer", values="quantity")

ValueError: ignored

In [ ]:
df.groupby(['Accessories', 'customer']).quantity.sum()

Accessories  customer
Ipad         Andrew      3
             Tom         2
Laptop       Andrew      3
             Peter       2
Tablet       Tobey       1
Name: quantity, dtype: int64

In [ ]:
df.set_index(["Accessories", "customer"])["quantity"]

Accessories  customer
Laptop       Andrew      1
             Andrew      2
Ipad         Tom         2
             Andrew      3
Tablet       Tobey       1
Laptop       Peter       2
Name: quantity, dtype: int64

#Q2. Find NaN Rows

You are required to find out all the rows containing one or more NaN values in a data frame `df`. Choose the correct code that will do the job in pandas.

df[df.isnull().any(axis=1)]

#Q3. Apply pandas

Given a function 'is_null' with the following implementation.

def is_null(x):
        return sum(x.isnull())
Choose the correct statement for a data frame 'df' when we execute the following code.

df.apply(is_null, axis=1)

Ans : Returns the number of missing values of df for each row.

#Q4. preprocess the dataframe

Problem Description

Given the data frame df as input, do the following steps for preprocessing:

1. Remove the row if all the columns have missing values.

2. Replace the missing values of "Roll_ID" column with 0 and "Name" column with "Anonymous"

3. Replace the missing values in "Marks" column with the median value of the column

4. Change the numerical columns (Roll_ID and Marks) to int datatype in the output

In [ ]:
df = pd.DataFrame ({
    'roll_id':[412, np.nan, 456, np.nan, 434, 429, 418],
    'name':['John', 'Mitra', 'Ritz', np.nan, 'Anny', 'Hema', np.nan],
    'marks':[np.nan, 32, 25, np.nan, 35, 28, 38]
})

In [ ]:
df

   roll_id   name  marks
0    412.0   John    NaN
1      NaN  Mitra   32.0
2    456.0   Ritz   25.0
3      NaN    NaN    NaN
4    434.0   Anny   35.0
5    429.0   Hema   28.0
6    418.0    NaN   38.0

In [ ]:
#df[df.isnull().all(axis=1)]
df.dropna(how='all', inplace=True)

In [ ]:
df

   roll_id   name  marks
0    412.0   John    NaN
1      NaN  Mitra   32.0
2    456.0   Ritz   25.0
4    434.0   Anny   35.0
5    429.0   Hema   28.0
6    418.0    NaN   38.0

In [ ]:
df

  roll_id   name marks
0     412   John   NaN
1     NaN  Mitra    32
2     456   Ritz    25
3     NaN    NaN   NaN
4     434   Anny    35
5     429   Hema    28
6     418    NaN    38

In [ ]:
df['roll_id'].replace('nan',0,inplace=True)

In [ ]:
df['name'].replace('nan','Anonymous',inplace=True)

In [ ]:
df['marks'].replace('nan',0,inplace=True)

In [ ]:
df['marks'].mean().round(2)

22.57

In [ ]:
df['marks'].replace(0,df['marks'].mean().round(2),inplace=True)

In [ ]:
df['marks'] = df['marks'].astype(int)

In [ ]:
df

   roll_id       name  marks
0      412       John     22
1        0      Mitra     32
2      456       Ritz     25
3        0  Anonymous     22
4      434       Anny     35
5      429       Hema     28
6      418  Anonymous     38

In [ ]:
df.astype({
    'roll_id':float,
    'marks':float
})

   roll_id       name  marks
0    412.0       John   22.0
1      0.0      Mitra   32.0
2    456.0       Ritz   25.0
3      0.0  Anonymous   22.0
4    434.0       Anny   35.0
5    429.0       Hema   28.0
6    418.0  Anonymous   38.0

In [ ]:
import numpy as np,pandas as pd
df = pd.DataFrame ({
    'roll_id':[412, np.nan, 456, np.nan, 434, 429, 418],
    'name':['John', 'Mitra', 'Ritz', np.nan, 'Anny', 'Hema', np.nan],
    'marks':[np.nan, 32, 25, np.nan, 35, 28, 38]
})

In [ ]:
df

   roll_id   name  marks
0    412.0   John    NaN
1      NaN  Mitra   32.0
2    456.0   Ritz   25.0
3      NaN    NaN    NaN
4    434.0   Anny   35.0
5    429.0   Hema   28.0
6    418.0    NaN   38.0

In [ ]:
df.dropna(how='all', inplace=True)
# Replace the missing values of "Roll_ID" column with 0 and "Name" column with "Anonymous"

df['roll_id'].fillna(0, inplace=True)

df['name'].fillna('Anonymous', inplace=True)
# Replace the missing values in "Marks" column with the median value of the column

df['marks'].fillna(0, inplace=True)

df['marks'].replace(0,df['marks'].mean(),inplace=True)
# Change the numerical columns (Roll_ID and Marks) to int datatype in the output
df.astype({
      'roll_id':int,
      'marks':int
      })

   roll_id       name  marks
0      412       John     26
1        0      Mitra     32
2      456       Ritz     25
4      434       Anny     35
5      429       Hema     28
6      418  Anonymous     38

#Q5. Data Manipulation

Which of the options is true about the mentioned statement where df is a pandas dataframe with column names: "Name", "Gender" and "column_c".

a. df['Gender'].isna().sum() gives the number of null values in the column "Gender".

b. df.isna().sum().sum() gives the number of null values in the whole dataframe.

c. df.loc[[3]].isna().sum().sum() gives the number of null values in the 4th row.

d. df.dropna(axis=1, how='all') and df.dropna(axis=1, how='any') are the methods to drop the columns having all or at least one of the values==Nan respectively.

e. df.fillna(value=replacement)will fill all the Nan values according to key, value pairs of replacement= {'Name': 0, 'Gender': 'unknown', 'column_C': -99999} where 'Name', 'Gender', and 'column_c' are the column names.

The code df['Gender'].isna().sum() calculates the total number of missing (NaN) values in the 'Gender' column of a DataFrame df

#All the options are correct

In [ ]:
df.isna().sum()

roll_id    2
name       2
marks      2
dtype: int64

df.isna().sum().sum()

In [ ]:
df.loc[[3]].isna().sum().sum()
#df.loc[[3]]

3

In [ ]:
replacement= {'Name': 0, 'Gender': 'unknown', 'column_C': -99999}
df.fillna(value=replacement)

   roll_id   name  marks
0    412.0   John    NaN
1      NaN  Mitra   32.0
2    456.0   Ritz   25.0
3      NaN    NaN    NaN
4    434.0   Anny   35.0
5    429.0   Hema   28.0
6    418.0    NaN   38.0

#Q6. fillna return type

Pick the correct statement/statements for the following code snippet.

In [ ]:
def fun(df):
    return df.fillna(1, inplace=True)

In [ ]:
df

   roll_id   name  marks
0    412.0   John    NaN
1      NaN  Mitra   32.0
2    456.0   Ritz   25.0
3      NaN    NaN    NaN
4    434.0   Anny   35.0
5    429.0   Hema   28.0
6    418.0    NaN   38.0

In [ ]:
fun(df)

In [ ]:
df

   roll_id   name  marks
0    412.0   John    1.0
1      1.0  Mitra   32.0
2    456.0   Ritz   25.0
3      1.0      1    1.0
4    434.0   Anny   35.0
5    429.0   Hema   28.0
6    418.0      1   38.0

#Q7. Org inc.

Problem Statement:

Given a dataframe consisting of organization's access id, return the count of invalid access ids.

The valid access ids should contain 'ORG' in the beginning.

For example:
Valid: 'ORG1234' / 'ORG4200'
Invalid: '1234' / 'OR1435'

In [ ]:
df = pd.DataFrame({'access_id': {0: 'ORG6684',   1: '4564',   2: 'ORG6995',   3: '2130',   4: '5839',   5: 'ORG1281',   6: 'ORG2651',   7: 'ORG9870',   8: 'ORG4089',   9: 'ORG3794'}}
)
df

  access_id
0   ORG6684
1      4564
2   ORG6995
3      2130
4      5839
5   ORG1281
6   ORG2651
7   ORG9870
8   ORG4089
9   ORG3794

In [ ]:
mask = ~df['access_id'].str.startswith('ORG')

In [ ]:
df[mask].count()

access_id    3
dtype: int64

#Q8. Sanity check

Problem Statement:

Given a dataframe of student's username for batch of 2022,

return the count of username which doesn't follow the below given guidelines:

The username should start with 'user_', and
The username should end with '_2022'

In [ ]:
df= pd.DataFrame({'name': ['elon', 'suzlon', 'keylon', 'dusk'], 'username': ['user_spaceboyelon_2022', 'user_suzlon123', 'tothemoon123_2022', 'user_duskmusk_2022']}
)

In [ ]:
df

     name                username
0    elon  user_spaceboyelon_2022
1  suzlon          user_suzlon123
2  keylon       tothemoon123_2022
3    dusk      user_duskmusk_2022

In [ ]:
df[(df['username'].str.startswith('user_'))&(df['username'].str.endswith('_2022'))]['username'].count()

2

#Q9. Location Divide

Problem Description:

Given a location dataframe, with a single column "City/tState", return the preprocessed dataframe with names of City and State separated.

In [ ]:
df = pd.DataFrame({"City\tState":['Kolkata\tWest Bengal', 'Chennai\tTamil Nadu', 'Hyderabad\tTelengana', 'Bangalore\tKarnataka']})
df

            City\tState
0  Kolkata\tWest Bengal
1   Chennai\tTamil Nadu
2  Hyderabad\tTelengana
3  Bangalore\tKarnataka

In [ ]:
df[['City','State']] = df['City\tState'].str.split('\t',expand=True)

In [ ]:
df.pop('City\tState')

0    Kolkata\tWest Bengal
1     Chennai\tTamil Nadu
2    Hyderabad\tTelengana
3    Bangalore\tKarnataka
Name: City\tState, dtype: object

In [ ]:
df

        City        State
0    Kolkata  West Bengal
1    Chennai   Tamil Nadu
2  Hyderabad    Telengana
3  Bangalore    Karnataka

#Q10. compute the age

Given below is an image containing information about a data frame.

The data frame has two columns, ID and birth_dates.

Assuming that the birth dates are convertible to DateTime format which of the following code snippets will compute the "age" column using the values in the "birth_rates" column?

In [ ]:
df = pd.DataFrame({'birth_dates':['06-09-1994']})

In [ ]:
df

  birth_dates
0  06-09-1994

In [ ]:
df["birth_dates"]= df["birth_dates"].astype("datetime64")
df["age"] = [pd.to_datetime('today').year-age.year for age in df["birth_dates"]]

In [ ]:
df

  birth_dates
0  06-09-1994

In [ ]:
df["age"] = pd.to_datetime("today").year - df["birth_dates"].dt.year

AttributeError: ignored

df

In [ ]:
df["birth_dates"]= df["birth_dates"].astype("datetime64")
df["age"] = 2022-df["birth_dates"].year

AttributeError: ignored

#Q11. Get the Month

As an educational institute, you need to keep a track of all the registered students. Here you're given the registration IDs and the corresponding dates of a batch of students. You need to return a DataFrame containing the columns as follows:

RID: Id of the student
RDate: Date of joining of the student
RMonth: Month of joining of the student
RYear: Year of joining of the student
RDay: Day of joining of the student

Input Format:

Number of testcases.
For each testcase there will be two lines of input.First-line contains the registration IDs of the students, and the following line contains the corresponding registration dates.

In [ ]:
import pandas as pd,numpy as np

In [ ]:
lines = '''56 92 29 93 55 32
2021-01-01 2021-02-12 2021-04-16 2021-01-22 2021-01-15 2021-02-26 '''.strip().split('\n')

In [ ]:
values = [i.split() for i in lines]

In [ ]:
values

[['56', '92', '29', '93', '55', '32'],
 ['2021-01-01',
  '2021-02-12',
  '2021-04-16',
  '2021-01-22',
  '2021-01-15',
  '2021-02-26']]

In [ ]:
df = pd.DataFrame(values).T

In [ ]:
df.columns=['RID','RDate']

In [ ]:
df['RMonth']= pd.to_datetime(df['RDate'])

In [ ]:
df.drop('RMonth',axis=1,inplace=True)

In [ ]:
df

  RID       RDate
0  56  2021-01-01
1  92  2021-02-12
2  29  2021-04-16
3  93  2021-01-22
4  55  2021-01-15
5  32  2021-02-26

In [ ]:
df['RYear']= pd.to_datetime(df['RDate']).dt.year

In [ ]:
df['RMonth']= pd.to_datetime(df['RDate']).dt.month

In [ ]:
df['RDate']= pd.to_datetime(df['RDate']).dt.day

In [ ]:
df

  RID  RDate  RMonth  RYear
0  56      1       1   2021
1  92     12       2   2021
2  29     16       4   2021
3  93     22       1   2021
4  55     15       1   2021
5  32     26       2   2021

In [ ]:
#reg_id, red_dates is in list of 2 columns
df = pd.DataFrame(zip(reg_id, reg_dates), columns=["RID", "RDate"])

# YOUR CODE GOES HERE

df['RDate'] = pd.to_datetime(df['RDate'])

df['RDay'] = df['RDate'].dt.day
df['RMonth'] = df['RDate'].dt.month
df['RYear'] = df['RDate'].dt.year

#Q12. Max registrations they asked?

You're given a record of students with their registration dates and registration ids. You're also given the marks scored by each of the students in Physics, Chemistry, and Mathematics. You need to find out the month that observed the maximum registrations. Then return the average marks scored in each subject. In case of a tie, select the month that comes first (lexicographically).

Sample's Explanation:
As it's visible from the dataframe December is most frequent therefore its first three-letter in upper case are printed first.
As December's frequency is 3, 3 is printed.
Then the average marks in chemistry, physics, and maths for the registration month December, are printed up to 2 decimal places. For eg. The IDs 498, 721, and 464 the average of chemistry is (52+56+50)/3.

In [60]:
import pandas as pd,numpy as np
df = pd.DataFrame({'Date':["2015-12-06", "2011-12-27", "2015-09-07", "2012-12-21", "2020-02-13", "2015-06-09"], 'RID':[498, 721, 375, 464, 813, 853], 'Phy':[22, 45, 1, 65, 22, 17], 'Chem':[52, 56, 32, 50, 24, 61], 'Math':[63, 37, 68, 62, 43 ,42]})

In [61]:
# Convert 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Extract the month
df['Month'] = df['Date'].dt.strftime('%B')

# Find the month with maximum registrations
max_reg_month = df['Month'].value_counts().idxmax()

# Filter records for the month with maximum registrations
df_filtered = df[df['Month'] == max_reg_month]

# Calculate average marks for each subject
avg_marks = df_filtered[['Phy', 'Chem', 'Math']].mean()


print("Month with maximum registrations:", max_reg_month)
print("Average marks in Physics:", avg_marks['Phy'])
print("Average marks in Chemistry:", avg_marks['Chem'])
print("Average marks in Mathematics:", avg_marks['Math'])

Month with maximum registrations: December
Average marks in Physics: 44.0
Average marks in Chemistry: 52.666666666666664
Average marks in Mathematics: 54.0

In [59]:
df

0      DEC
1        3
2    52.67
3     44.0
4     54.0
dtype: object

In [4]:
df['month'] = pd.to_datetime(df['Date']).dt.month

In [8]:
import calendar as c

In [ ]:
lambda x : c.month_name(x)

In [10]:
df['month_name'] = df['month'].apply(lambda x: c.month_name[x])

In [18]:
df['month_name'].value_counts() == df['month_name'].value_counts().max()

December      True
September    False
February     False
June         False
Name: month_name, dtype: bool

In [32]:
df['month_name'].value_counts().idxmax()

'December'

In [ ]:
df['month_name'].value_counts().max()

In [36]:
df_new = df[df['month_name'] == df['month_name'].value_counts().idxmax()]

In [37]:
df_new

         Date  RID  Phy  Chem  Math  month month_name
0  2015-12-06  498   22    52    63     12   December
1  2011-12-27  721   45    56    37     12   December
3  2012-12-21  464   65    50    62     12   December

In [55]:
d = df_new['Phy'].mean().round(2)

In [54]:
c = df_new['Chem'].mean().round(2)

In [56]:
e = df_new['Math'].mean().round(2)

In [52]:
#x = df_new['month_name'].unique()
a = df_new['month_name'].str[:3].str.upper()[0]

In [53]:
b = df_new['month'].count()

In [57]:
df = pd.Series([a,b,c,d,e])

In [58]:
df

0      DEC
1        3
2    52.67
3     44.0
4     54.0
dtype: object

#Additional problesm

In [1]:
import pandas as pd, numpy as np,

The number of unique customers who made a purchase on 22 June 2011 is?

In [43]:
df = pd.read_csv('sales_dataset.txt')

In [44]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
23210,491186,21804,WHITE CHRISTMAS GARLAND STARS TREES,1,2009-12-10 12:21:00,3.75,15889.0,United Kingdom
23211,491186,22125,UNION JACK HOT WATER BOTTLE,1,2009-12-10 12:21:00,5.95,15889.0,United Kingdom
23212,491186,22149,FELTCRAFT 6 FLOWER FRIENDS,1,2009-12-10 12:21:00,2.10,15889.0,United Kingdom
23213,491186,22118,JOY WOODEN BLOCK LETTERS,2,2009-12-10 12:21:00,4.95,15889.0,United Kingdom
23214,491186,21755,LOVE BUILDING BLOCK WORD,1,2009-12-10 12:21:00,5.00,NaN,NaN

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279889 entries, 0 to 279888
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      279889 non-null  object
 1   StockCode    279889 non-null  object
 2   Description  277844 non-null  object
 3   Quantity     279889 non-null  int64
 4   InvoiceDate  279889 non-null  object
 5   Price        279888 non-null  float64
 6   Customer ID  219457 non-null  float64
 7   Country      279888 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 17.1+ MB

In [45]:
#pd.to_datetime (df['InvoiceDate']).dt.year
#pd.to_datetime(df['InvoiceDate']).dt.year - cant do
#df['date_column'] = df['datetime_column'].apply(lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S").date())

from datetime import datetime
#df['Date'] = df['InvoiceDate'].apply(lambda x : datetime.strptime(x, "%Y-%m-%d")).date()

In [46]:
#df['Date'] = pd.to_datetime(df['InvoiceDate']).dt.date

In [27]:
def custom_datetime_parser(x):
    try:
        return datetime.strptime(x, "%Y-%m-%d %H:%M:%S").date()
    except ValueError:
        return None  # Handle non-standard values

# Apply the custom function to the 'InvoiceDate' column
df['Date'] = df['InvoiceDate'].apply(custom_datetime_parser)

In [41]:
df[df['InvoiceDate'].str.startswith('2011')]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country, Date]
Index: []

In [42]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Date
279884,516626,20914,SET/5 RED SPOTTY LID GLASS BOWLS,6,2010-07-22 08:24:00,2.95,13402.0,United Kingdom,2010-07-22
279885,516626,22262,FELT EGG COSY CHICKEN,12,2010-07-22 08:24:00,0.85,13402.0,United Kingdom,2010-07-22
279886,516626,22263,FELT EGG COSY LADYBIRD,12,2010-07-22 08:24:00,0.85,13402.0,United Kingdom,2010-07-22
279887,516626,22260,FELT EGG COSY BLUE RABBIT,12,2010-07-22 08:24:00,0.85,13402.0,United Kingdom,2010-07-22
279888,516626,21983,PACK OF 12 BLUE PAISLEY TISSUES,48,20,NaN,NaN,NaN,None

In [48]:
url = 'https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/003/720/original/sales_dataset.csv?1651739276'
df = pd.read_csv(url)

In [49]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [53]:
df[df['InvoiceDate'].str.startswith('2011-06-22')]['Customer ID'].nunique()

57

#Q2. Highest sales date in France

Which date has the highest sales(total price) in France?

Date: YYYY-MM-DD

In [68]:
url = 'https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/003/714/original/sales_dataset.csv?1651726379'
df = pd.read_csv(url)

In [71]:
df['total price'] = df['Quantity']*df['Price']

In [76]:
df['total price'] == df['total price'].max()

0          False
1          False
2          False
3          False
4          False
           ...
1067366    False
1067367    False
1067368    False
1067369    False
1067370    False
Name: total price, Length: 1067371, dtype: bool

In [78]:
df[df['Country'] == 'France']['total price'].max()

4161.06

In [80]:
df[df['Price'] == df[df['Country'] == 'France']['Price'].max()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,total price
947835,573077,M,Manual,1,2011-10-27 14:13:00,4161.06,12536.0,France,4161.06
947836,C573079,M,Manual,-2,2011-10-27 14:15:00,4161.06,12536.0,France,-8322.12
947838,573080,M,Manual,1,2011-10-27 14:20:00,4161.06,12536.0,France,4161.06