<a href="https://colab.research.google.com/github/knagabharathi/Python/blob/main/Pandas_modify_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np
#import google.colab as gc

from google.colab import drive
drive.mount('/content/mount')

Drive already mounted at /content/mount; to attempt to forcibly remount, call drive.mount("/content/mount", force_remount=True).

In [11]:
df=pd.read_csv("/content/mount/MyDrive/mckinsey.csv")
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [18]:
df.rename({'country':'Country'},axis=1)

          Country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [21]:
df = df.rename({'country':'Country'},axis=1)
df.head()

       Country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [23]:
df =df.rename({'year':'Year'},axis=1)
df

          Country  Year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [26]:
df.rename({'population':'Population','continent':'Continent'},axis=1,inplace=True)
df

          Country  Year  Population Continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

Deletion of columns

In [27]:
df.drop(['life_exp'],axis=1)

          Country  Year  Population Continent     gdp_cap
0     Afghanistan  1952     8425333      Asia  779.445314
1     Afghanistan  1957     9240934      Asia  820.853030
2     Afghanistan  1962    10267083      Asia  853.100710
3     Afghanistan  1967    11537966      Asia  836.197138
4     Afghanistan  1972    13079460      Asia  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa  706.157306
1700     Zimbabwe  1992    10704340    Africa  693.420786
1701     Zimbabwe  1997    11404948    Africa  792.449960
1702     Zimbabwe  2002    11926563    Africa  672.038623
1703     Zimbabwe  2007    12311143    Africa  469.709298

[1704 rows x 5 columns]

In [28]:
df

          Country  Year  Population Continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
# # 1st method
# df.drop(["Continent"],axis=1,inplace=True)
# # 2nd method
# df=df.drop(["Continent"],axis=1)

Creating New column

In [31]:
df['Year']

0       1952
1       1957
2       1962
3       1967
4       1972
        ...
1699    1987
1700    1992
1701    1997
1702    2002
1703    2007
Name: Year, Length: 1704, dtype: int64

In [34]:
df['Year+7']= df['Year']+7
df

          Country  Year  Population Continent  life_exp     gdp_cap  Year+7
0     Afghanistan  1952     8425333      Asia    28.801  779.445314    1959
1     Afghanistan  1957     9240934      Asia    30.332  820.853030    1964
2     Afghanistan  1962    10267083      Asia    31.997  853.100710    1969
3     Afghanistan  1967    11537966      Asia    34.020  836.197138    1974
4     Afghanistan  1972    13079460      Asia    36.088  739.981106    1979
...           ...   ...         ...       ...       ...         ...     ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306    1994
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786    1999
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960    2004
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623    2009
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298    2014

[1704 rows x 7 columns]

In [35]:
df['Year+10'] = df['Year']+10
df

,Country,Year,Population,Continent,life_exp,gdp_cap,Year+7,Year+10
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,1959,1962
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,1964,1967
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,1969,1972
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,1974,1977
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,1979,1982
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306,1994,1997
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786,1999,2002
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960,2004,2007
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623,2009,2012
1703,Zimbabwe,2007,12311143,Africa,43.487,469.709298,2014,2017

In [36]:
df.shape

(1704, 8)

In [37]:
df['new_column']= [i for i in range(1704)]

In [38]:
df

,Country,Year,Population,Continent,life_exp,gdp_cap,Year+7,Year+10,new_column
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,1959,1962,0
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,1964,1967,1
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,1969,1972,2
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,1974,1977,3
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,1979,1982,4
...,...,...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306,1994,1997,1699
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786,1999,2002,1700
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960,2004,2007,1701
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623,2009,2012,1702
1703,Zimbabwe,2007,12311143,Africa,43.487,469.709298,2014,2017,1703

Basic operations in Rows

In [39]:
df.index

RangeIndex(start=0, stop=1704, step=1)

In [40]:
df.index.values

array([   0,    1,    2, ..., 1701, 1702, 1703])

In [47]:
df[4:6]

,Country,Year,Population,Continent,life_exp,gdp_cap,Year+7,Year+10,new_column
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,1979,1982,4
5,Afghanistan,1977,14880372,Asia,38.438,786.113360,1984,1987,5

In [48]:
df.loc[4:6,'Country':'Population']#explicit

       Country  Year  Population
4  Afghanistan  1972    13079460
5  Afghanistan  1977    14880372
6  Afghanistan  1982    12881816

In [49]:
df.iloc[4:6,0:3]#implicit

       Country  Year  Population
4  Afghanistan  1972    13079460
5  Afghanistan  1977    14880372